//@version=4
strategy("52 highs",process_orders_on_close=true,initial_capital=150)

startDate = input(title="Start Date", type=input.integer,
     defval=1, minval=1, maxval=31)
startMonth = input(title="Start Month", type=input.integer,
     defval=1, minval=1, maxval=12)
startYear = input(title="Start Year", type=input.integer,
     defval=2015, minval=1800, maxval=2100)

endDate = input(title="End Date", type=input.integer,
     defval=31, minval=1, maxval=31)
endMonth = input(title="End Month", type=input.integer,
     defval=7, minval=1, maxval=12)
endYear = input(title="End Year", type=input.integer,
     defval=2021, minval=1800, maxval=2100)

inDateRange = (time >= timestamp(syminfo.timezone, startYear,
         startMonth, startDate, 0, 0)) and
     (time < timestamp(syminfo.timezone, endYear, endMonth, endDate, 0, 0))


weekly_hc = highest(close,52)
trailing_stop = lowest(close,10)



strategy.entry("Long", strategy.long, strategy.equity/close, when=close>=weekly_hc and inDateRange)
//strategy.close("Long",when=current_profit>=60 and inDateRange)
strategy.exit("Long", stop=trailing_stop)
